/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jitian_jni_JiTianEncrypt */

#ifndef _Included_com_jitian_jni_JiTianEncrypt
#define _Included_com_jitian_jni_JiTianEncrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jitian_jni_JiTianEncrypt
 * Method:    getEncryptData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jitian_jni_JiTianEncrypt_getEncryptData
  (JNIEnv *, jobject);

/*
 * Class:     com_jitian_jni_JiTianEncrypt
 * Method:    getCertifiedData
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_jitian_jni_JiTianEncrypt_getCertifiedData
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif